version: '3.9'
services:
  mysql-dev:
    image: mysql:5.7
    restart: always
    tty: true
    volumes:
      - ../../../.volumes/vertice/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=cryptotrader
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"